### ISSUE TITLE
Practica de GPS con Realidad Aumentada

### ISSUE THREAD

**Issue by Itzelzun** [SistemasTecTlaxiaco/practica-de-gps-equipo-francisco#2]
[Practica de Geolocalizacion.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-equipo-francisco/files/6448335/Practica.de.Geolocalizacion.pdf)

**Comment by AxayacatlS** [comment]
Calificación: 20
Excelente trabajo ;)

**Comment by josealfredo79** [comment]
bien hecho y revisado.
